// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// segment //
// ------- //

#define segment_wrap_target 0
#define segment_wrap 5

static const uint16_t segment_program_instructions[] = {
            //     .wrap_target
    0x8080, //  0: pull   noblock         side 0     
    0xa027, //  1: mov    x, osr          side 0     
    0x6208, //  2: out    pins, 8         side 1     
    0x6408, //  3: out    pins, 8         side 2     
    0x6808, //  4: out    pins, 8         side 4     
    0x7008, //  5: out    pins, 8         side 8     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program segment_program = {
    .instructions = segment_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config segment_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + segment_wrap_target, offset + segment_wrap);
    sm_config_set_sideset(&c, 4, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void segment_program_init(PIO pio, uint sm, uint offset, uint first_segment_pin, uint first_digit_pin) {
    const int segment_pins = 8;
    const int digit_pins = 4;

    // Machine configuration: out pins, sideset pins, and shift direction.
    pio_sm_config c = segment_program_get_default_config(offset);
    sm_config_set_out_pins(&c, first_segment_pin, segment_pins);
    sm_config_set_sideset_pins(&c, first_digit_pin);
    sm_config_set_out_shift(&c, false, false, 32); // Shift to the left

    // Attach all pins to the PIO peripheral
    for (int pin = first_segment_pin; pin < first_segment_pin + segment_pins; pin++) {
        pio_gpio_init(pio, pin);
    }
    for (int pin = first_digit_pin; pin < first_digit_pin + digit_pins; pin++) {
        pio_gpio_init(pio, pin);
    }

    // Configure all pins as outputs
    pio_sm_set_consecutive_pindirs(pio, sm, first_segment_pin, segment_pins, true);
    pio_sm_set_consecutive_pindirs(pio, sm, first_digit_pin, digit_pins, true);

    // Run at 2000Hz:
    float div = (float)clock_get_hz(clk_sys) / 2000; 
    sm_config_set_clkdiv(&c, div);

    // Start the machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
